<?php

return [
    'languages' => [
        'en' => 'English',
        'de' => 'German',
        // 'fr' => 'French',
        // 'es' => 'Spanish',
        // 'it' => 'Italian',
        'hr' => 'Croatian',
    ],
    'date_formats' => [
        'Y-m-d' => 'yyyy-mm-dd  (2025-12-21)',
        'd.m.Y' => 'dd.mm.yyyy  (21.12.2025)',
        // 'm.d.Y' => 'mm.dd.yyyy  (12.21.2025)',
    ],
    'currencies' => [
        /*
        'USD' => 'US Dollar',
        'EUR' => 'Euro',
        'GBP' => 'British Pound Sterling',
        'CAD' => 'Canadian Dollar',
        'AUD' => 'Australian Dollar',
        'CHF' => 'Swiss Franc',
        'CNY' => 'Chinese Yuan Renminbi',
        'INR' => 'Indian Rupee',
        'JPY' => 'Japanese Yen',
        'BRL' => 'Brazilian Real',
        'MXN' => 'Mexican Peso',
        'ZAR' => 'South African Rand',
        'HKD' => 'Hong Kong Dollar',
        'SGD' => 'Singapore Dollar',
        'SEK' => 'Swedish Krona',
        'NOK' => 'Norwegian Krone',
        'NZD' => 'New Zealand Dollar',
        'RUB' => 'Russian Ruble',
        'SAR' => 'Saudi Riyal',
        'KRW' => 'South Korean Won',
        */
        'AUD' => 'AUD',
        'BRL' => 'BRL',
        'CAD' => 'CAD',
        'CHF' => 'CHF',
        'CNY' => 'CNY',
        'EUR' => 'EUR',
        'GBP' => 'GBP',
        'HKD' => 'HKD',
        'INR' => 'INR',
        'JPY' => 'JPY',
        'KRW' => 'KRW',
        'MXN' => 'MXN',
        'NOK' => 'NOK',
        'NZD' => 'NZD',
        'RUB' => 'RUB',
        'SAR' => 'SAR',
        'SEK' => 'SEK',
        'SGD' => 'SGD',
        'USD' => 'USD',
        'ZAR' => 'ZAR'
    ],
    'default_currency' => 'EUR',
    'default_language' => 'en',
    'default_timezone' => 'UTC',
    'default_date_format' => 'd.m.Y',
    'place_suggest_min_length' => env('PLACE_SUGGEST_MIN_LENGTH', 3),
    'location_suggest_min_length' => env('LOCATION_SUGGEST_MIN_LENGTH', 3),
    'debounce_delay' => env('DEBOUNCE_DELAY', 300), // in milliseconds
    'badges_per_item' => env('BADGES_PER_ITEM', 3),
    'badges_per_demo_user' => env('BADGES_PER_DEMO_USER', 3),
    'badges_per_basic_user' => env('BADGES_PER_BASIC_USER', 10),
    'badges_per_premium_user' => env('BADGES_PER_PREMIUM_USER', 50),
    
    // Maintenance mode configuration
    'maintenance_lock_up' => env('MAINTENANCE_LOCK_UP', false),
];
